[package]
name = "nova"
version = "0.1.13"
description = "Nova - AI Chat Client"
authors = ["wangxf"]
edition = "2021"

[lib]
name = "nova_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "tray-icon"] }
tauri-plugin-notification = "2"
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "6"
tokio = { version = "1", features = ["full"] }
axum = "0.8"
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "native-tls", "stream"] }
xcap = "0.9"
image = "0.25"
glob = "0.3"
regex = "1"
tauri-plugin-process = "2"
sha2 = "0.10"
ort = { version = "2.0.0-rc.13", default-features = false, features = ["load-dynamic"] }
tokenizers = { version = "0.23.1", default-features = false, features = ["onig"] }

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2"
